spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always

logging:   
  level:
    root: INFO
    ua.schoolconsoleapp: DEBUG
  file:
    name: logs/application.log
flyway:
  enabled: true
  baseline-on-migrate: true  
  locations: classpath:db/migration 
  default-schema: school
      

