spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always
  flyway:
    enabled: true
    baseline-on-migrate: true  
    locations: classpath:db/migration 
    default-schema: school
logging:   
  level:
    root: INFO
    ua.schoolconsoleapp: DEBUG
  file:
    name: logs/application.log

      

